# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Frigid Light Photography
tagline:             Adventure Photogaphy by David Howland
url:                 http://frigidlight.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              David Howland
  email:             david@frigidlight.com

# Custom vars
# version:             2.0.0
# github:
  # repo:              https://github.com/poole/poole
